before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: MVb0z2PkGUHOaFcAFhyJFegMFwik3Lh6DHQd9YiYDxh5TVrd8UDLM/yiULBBucAjd6DA2xN1bbxRSe/tATNjl/9236E9TD4AB/tDVgHTkEWZA9WQAzseOobDHIGS8MeICKK9ywxBL0ewgJZbvRWZGwCLQIf1DIYSasHT5mHbfFyvgrWNz8tFT7Q8LebtN6FmVCH2LbjNTeuZIOj7PQiJ10Y0epqwbEZnqpxe2BWI0Y0aUWIICzeXXGLlV31abmzgPkiBQ1LZ+IP4tKmNpzG9IRAJzNBG/w59MidHZeknSWz1JMbvkBX5afsV9YCAcGJ1FK8tD35r7veNPq5AwLHqjUxynjBXJzKN/d1qNDo8TcN0hudrR8uON3NQfNALE+AJPlrE4Q0Cj7aZzQvYH/9XYWhAXekvkNoV+ioFX7DISG6GU2uLva2LHVwFpJmp7xxOiqKpcEieVEcSJ1sclqGV8y2hYabrpr3kekeEY7OfPxd0uOZjcDshOy88eVIcsaorhBhdvoUHC6na8/DD4fMcUumlOHN5Jg5l/A9+Gic2Zt/+Pndb+zLs+068QRJWcpTU3WOSc9zlJAbXFuDeQG6QK3Db92QI22RCKIdS5Zpm5Nq/i4qt9p506RVSO8QR7VP7OIYkg0F0P1xtte+XwHnkdVL6tfFHf0r73y6lzR9VqOI= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
